wes/urls.py
from xml.dom.minidom import Document
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wesapp.urls'))
]

wesapp/urls.py
from django.contrib import admin
from django.urls import path
from wesapp import views
from django.conf import settings
from django.conf.urls.static import static
from .views import AddPostView, DeletePostView, UpdatePostView, home, register, login_user, logout_user, about, footer, home01, subscription, profile, HomeView, ArticleDetail, feed, home_body, UpdatePostView, DeletePostView, news, contact, premium_access, like_post, AddCommentView, mypost, user_change_pass

admin.site.site_header = "Mehdi Alam"
admin.site.site_title = 'title'
admin.site.index_title = "Welcome!!"

urlpatterns = [
    path('base', home, name='home'),
    path('news/', news, name='news'),

    path('contact', contact, name='contact'),

    path('premium_access/', premium_access, name='premium_access'),
    path('', home01, name='home01'),
    path('w', home_body, name='home_body'),
    path('register/', register, name='register'),

    path('login_user', login_user, name="login_user"),
    path('logout_user', logout_user, name="logout_user"),
    path('about/', about, name="about"),
    path('footer/', footer, name="footer"),
    path('subscription/', subscription, name="subscription"),
    path('profile/', profile, name="profile"),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('articleDetail/<int:pk>', ArticleDetail.as_view(), name='articleDetail'),
    # path('feed/', feed, name='feed'),

    path('mypost/', mypost, name='mypost'),

    path('feed/', HomeView.as_view(), name='feed'),
    path('articleDetail/edit/<int:pk>',
         UpdatePostView.as_view(), name='update_post'),

    path('articleDetail/<int:pk>remove',
         DeletePostView.as_view(), name='delete_post'),
    path(r'^like/$', like_post, name="like_post"),

    path('articleDetail/<int:pk>/comment',
         AddCommentView.as_view(), name="add_comment"),

    path('changepass/', views.user_change_pass, name='changepass')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wesapp/models.py
from audioop import reverse
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
from django import forms
from django.utils.timezone import now


class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(
        null=True, blank=True, upload_to="images/")

    author = models.CharField(max_length=13)
    content2 = models.TextField()
    likes = models.ManyToManyField(User, related_name='blog_posts',)

    REQUIRED_FIELDS = ["title", "author"]

    def __str__(self):
        return 'Message from ' + self.title + ' by ' + str(self.author)

    def get_absolute_url(self):
        return reverse('home01')

    def total_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)


class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=14)
    email = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return 'Message from ' + self.name + ' - ' + self.email

wesapp/views.py
from dataclasses import field
from pdb import post_mortem
from urllib import response

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
# Create
from django.http import HttpResponse, HttpResponseRedirect
# your views here.
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from .models import Contact
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from .models import Post, Comment
import requests
API_KEY = '2c0f2edec2944d49a72c0fb05ad44397'

# def HomeView(ListView):
#     model = Post
#     template_name = 'feed.html'


class HomeView(ListView):
    model = Post
    template_name = 'feed.html'


# def header_image(self):
#     if self.image and hasattr(self.image, 'url'):
#         return self.image.url


def home(request):
    return render(request, 'home.html')


def premium_access(request):
    return render(request, 'premium_access.html')


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = f'Welcome to WeStocks ,{name}'
        message = 'We got your problem,we will try to communicate with you within 24 hours, Thanks'
        recepient = email
        send_mail(subject, message, settings.EMAIL_HOST_USER,
                  [recepient], fail_silently=False)
        phone = request.POST['phone']
        content = request.POST['content']

        if len(name) < 2 or len(email) < 3 or len(phone) < 10 or len(content) < 4:
            messages.error(request, "Please fill the form correctly")
        else:
            contact = Contact(name=name, email=email,
                              phone=phone, content=content)
            contact.save()
            messages.error(request, 'your message has been successfully sent')

    return render(request, 'contact.html')


def news(request):
    url = f'https://newsapi.org/v2/everything?q=market&apiKey={API_KEY}'
    data = requests.get(url)
    response = data.json()
    articles = response['articles']
    context = {'articles': articles}
    return render(request, 'news.html', context)


def like_post(request):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    return HttpResponseRedirect(reverse('feed'))


def home_body(request):
    return render(request, 'home_body.html')


def about(request):
    return render(request, 'about.html')


def feed(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes,
    }

    return render(request, 'feed.html', context)


def footer(request):
    return render(request, 'footer.html')


def home01(request):
    return render(request, 'home01.html')


def subscription(request):
    return render(request, 'subscription.html')


def profile(request):
    return render(request, 'profile.html')


def register(request):

    if request.method == 'POST':

        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        subject = 'Welcome to WeStocks'
        message = 'Thank you for joining us'
        recepient = email
        send_mail(subject, message, settings.EMAIL_HOST_USER,
                  [recepient], fail_silently=False)
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already exist')
                return redirect(register)
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email is already exist')
                return redirect(register)
            else:
                user = User.objects.create_user(
                    username=username, password=password, email=email, first_name=first_name, last_name=last_name)
                user.set_password(password)
                user.is_staff = True
                user.save()

                messages.info(request, 'you have registered successfully!!!')
                return redirect(register)
        else:
            messages.info(request, ' password do not match')
            return redirect(register)

    else:
        return render(request, 'register.html')


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('home01')
        else:
            messages.info(request, 'Invalid Username or Password')
            return redirect('login_user')
    else:
        return render(request, 'login.html')


def logout_user(request):
    auth.logout(request)
    return redirect('home01')


class AddPostView(CreateView):
    model = Post
    template_name = 'add_post.html'
    fields = ['title', 'author', 'content2']
    # fields = ('title', 'body')
    success_url = reverse_lazy('feed')


class ArticleDetail(DetailView):
    model = Post
    template_name = 'articles_contain.html'


class UpdatePostView(UpdateView):
    model = Post
    template_name = 'update_post.html'
    fields = ['title', 'content2']
    success_url = reverse_lazy('feed')


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('feed')


class AddCommentView(CreateView):
    model = Comment
    template_name = 'add_comment.html'
    # fields = ['name', 'body']
    success_url = reverse_lazy('feed')

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

    success_url = reverse_lazy('feed')
    fields = ('name', 'body')


def mypost(request):
    posts = Post.objects.filter(author=request.user.username)
    return render(request, 'mypost.html', {'myposts': posts})


def user_change_pass(request):
    if request.method == 'POST':
        fm = PasswordChangeForm(user=request.user, data=request.POST)
        if fm.is_valid():
            fm.save()
            update_session_auth_hash(request, fm.user)
            return HttpResponseRedirect('/profile/')
    else:
        fm = PasswordChangeForm(user=request.user)
    return render(request, 'changepass.html', {'form': fm})

wesapp/templates/about.html
{% extends 'base.html' %}
 
{% block content %}
  

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>



.column {
  float: left;
  width: 23%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}

.container {
  padding: 0 6px;
  
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
.row{
    padding: 0px 66px;
}

.cont{
  display: flex;
  margin-left: 100px;
}
.whole-cont{
  margin-top: 10px;
  margin-bottom: 100px;
}

</style>
</head>
<body style="padding-top: 33px;">
<div class="whole-cont">
<div class="about-section">
  <h1>About Us </h1>
  <p>Some text about who we are and what we do.</p>
  <p>Resize the browser window to see that this page is responsive by the way.</p>
</div>

<h2 style="text-align:center; margin-bottom: 33px; ">Our Team</h2>
<div class="cont">
  <div class="column">
    <div class="card">
      
      <div class="container">
        <h2>Mehdi Alam</h2>
        <p class="title">Back-end Developer</p>
        
        <p>mehdialam2002@gmail.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
     
      <div class="container">
        <h2>Manish Gupta</h2>
        <p class="title">Content deliver</p>
        
        <p>manishgupta39@gmail.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
  
  <div class="column">
    <div class="card">
     
      <div class="container">
        <h2>Sushant Kumar</h2>
        <p class="title">Graphic Designer</p>
        
        <p>sushant89@gmail.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
     
      <div class="container">
        <h2>Nilambar </h2>
        <p class="title">Front-end Developer</p>
        
        <p>nil324@gmail.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>
</div>

</body>
</html>


{% endblock  %}

wesapp/templates/add_comment.html
<!-- 





    

<h1>Edit Blog Post</h1>


<form action="" method="post" encrypt="multipart/form-data">
   <input type="hidden" name="csrfmiddlewaretoken" value="yNGRoHrR9S4CEkYoSrtwg7eTGhesia6hcsoSOG8z6xhVpScBCp2BfdMW0hfoykkI">
   <p><label for="id_post">Post:</label> <select name="post" required id="id_post">
  <option value="" selected>---------</option>

  <option value="26">Message from de by Manish Gupta</option>

  <option value="27">Message from Union Budget 2022 by Mehdi</option>

  <option value="28">Message from How much Tax is paid on Bond by Manish</option>

  <option value="29">Message from wew by ddd</option>

  <option value="30">Message from sdakjfds by askfdska</option>

  <option value="31">Message from raaaaaaaaaaaa by aaaaaaaa</option>

  <option value="32">Message from a by a</option>

  <option value="35">Message from loove by LOVE</option>

</select></p>
<p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="255" required id="id_name"></p>
<p><label for="id_body">Body:</label> <textarea name="body" cols="40" rows="10" required id="id_body">
</textarea></p>
   
   
   <button>Update</button>
</form>
 -->


 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
     <title>Document</title>
     <style>
 
         .forrm {
             margin-top: 40px;
             margin-left: 300px;
             margin-right: 400px;
             padding: 19px;
             box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 7px;
 
         }
         .post_cancel{
             display: flex;
             justify-content: space-between;
         }
         
     </style>
 </head>
 <body>
 <!--    
     
 
     
     <form method="post" encrypt="multipart/form-data"  class="forrm">
         <input type="hidden" name="csrfmiddlewaretoken" value="yNGRoHrR9S4CEkYoSrtwg7eTGhesia6hcsoSOG8z6xhVpScBCp2BfdMW0hfoykkI">
         <h1>Add Blog Post</h1>
         <input class="form-control"  type="hidden"  >
        <p><label class="form-label" for="id_title"><strong>Title:</strong></label> <input type="text" name="title" maxlength="255" required id="id_title"></p>
    
     <p><label for="id_content"><strong>Content:</strong></label> <input type="text" name="content" maxlength="100" required id="id_content"></p>
     <p><label for="id_author"><strong>Author:</strong></label> <input type="text" name="author" maxlength="13" required id="id_author"></p>
     <p><label for="id_header_image"><strong>Image:</strong></label> <input type="file" name="header_image" accept="image/*" id="id_header_image"></p>
 
     <div class="post_cancel">
         <button class="btn btn-sm
      btn-success">Post</button>
     <a class="btn btn-sm
         btn-danger" href="/feed">Cancel</a>
     </div>
      </form> -->
 
 <div class="forrm">

 

<h1>Add Comment</h1>
<br><br>
<div class="form-group">
    <form action="" method="post">
{% csrf_token %}
    
<p><label for="id_name">Name:</label> 
    <input class="form-control" type="text"name="name" value="{{request.user.username}}" readonly placeholder="Your name" maxlength="255" required id="id_name"></p>
<p><label for="id_body">Comment</label> <textarea class="form-control" placeholder="Your Comment" name="body" cols="40" rows="4" required id="id_body">
</textarea></p>
        <button class="btn btn-success">Add Comment</button>
        <a class="btn btn-danger mx-4"  href="/feed">Cancel</a>
    </form>
    
</div>
</div>



 
 
 
          
 
 
 
<!--  
 <form action="" method="post" class="forrm">
     <h1>Comment on Blog Post</h1>
         <input type="hidden" name="csrfmiddlewaretoken" value="yNGRoHrR9S4CEkYoSrtwg7eTGhesia6hcsoSOG8z6xhVpScBCp2BfdMW0hfoykkI">
    <input class="form-control" type="hidden" >
    <p><label for="id_title">Title:</label> <input class="form-control" type="text" name="title" maxlength="255" required id="id_title"></p>
    <p><label for="id_content2">Content:</label> <textarea class="form-control" name="content2" cols="40" rows="10" required id="id_content2">
 </textarea></p>
 <p><label for="id_header_image">Header image:</label> <input type="file" name="header_image" accept="image/*" id="id_header_image"></p>
 <p><label for="id_author">Author:</label> <input class="form-control" type="text" name="author" maxlength="13" required id="id_author"></p>
 
    
    
 <div class="post_cancel">
     <button class="btn btn-sm
  btn-success">Add Comment</button>
 <a class="btn btn-sm
     btn-danger" href="/feed">Cancel</a>
 </div>
 </form>
  -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
 
 
 
 </body>
 </html>

wesapp/templates/articles_contain.html
<img src="{{ post.header_image.url }}" >

{{post.title_tag}}

<h1>Title: {{post.title}}</h1>

<h2>By:{{ post.author}}</h2>


<a class="btn btn-secondry" href="{% url 'homeview' %}">Back</a>

wesapp/templates/changepass.html
{% extends 'base.html' %}
{% block content %}
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
</head>
<body style="margin-top: 100px; ">
    <form style="margin-bottom: 200px; margin-left: 200px; margin-right: 500px;" action="" method="post" novalidate>
{% csrf_token %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors  %}
<p>{{error}}</p>
{% endfor %}
{% endif %}

{% for fm in form  %}
{{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br><br>
{% endfor %}
<div style="display: flex; gap: 500px;">
    
<input class="btn btn-success" type="submit" value="Save" >
    <a class="btn btn-danger" href="/profile">Cancel</a>
</div>


    </form>

</body>
</html> 



<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">


<!-- 


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <style>y
        .formm{
            margin: 100px 400px 200px 400px;

        }
    </style>
</head>
<body>

    <form  name="csrfmiddlewaretoken" value="pvM4q4dUpmCosyL7lDpmvpmCHjAXjhRkhuPZzX7D2BHuwuUo9Wxi7fpkMFkaBfxA" class="formm" action="" method="post" novalidate>
        {% csrf_token %}
<input class="form-control" type="hidden" >

<label for="id_old_password">Old password:</label>

 <input class="form-control"  type="password" name="old_password" autocomplete="current-password" autofocus required id="id_old_password">  <br>

<label for="id_new_password1">New password:</label> 

<input class="form-control"  type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1"> 
 <br>

<label for="id_new_password2">New password confirmation:</label> 

<input class="form-control"  type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2"> 
 <br>
 <input class="btn btn-success" type="submit" value="Save" >

    
    </form>

</body>
</html> -->

{% endblock %}

wesapp/templates/contact.html
{% extends 'base.html' %}
{% block content %}

<style>
    .contactt{
    
        margin: 130px 200px 80px 200px;
    }
</style>


<!--Section: Contact v.2-->
<section  class=" contactt">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div  class="row ">

        <!--Grid column-->
        <div   class="col-md-9 mb-md-0 mb-5 ">
            <form id="contact-form" name="contact-form" action="/contact" method="POST">
                {% csrf_token %}
                <div  >
                    {% for message in messages %}
                    <div class="alert alert-danger "role="alert">
                        {{message}}
                    </div>
                    {% endfor %}
                    </div>

                <!--Grid row-->
                <div style="margin-bottom: 16px;" class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="name" >Your name</label>
                            <input type="text" id="name" name="name" class="form-control">
                            
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="email" class="">Your email</label>
                            <input type="email" id="email" name="email" class="form-control">
                            
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div style="margin-bottom: 16px;" class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <label for="phone" class="">Phone</label>
                            <input type="phone" id="phone" name="phone" class="form-control">
                            
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div style="margin-bottom: 16px;" class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <label for="message">Describe your issue</label>
                            <textarea type="content" id="content" name="content" rows="2" class="form-control md-textarea"></textarea>
                            
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center mt-3 text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                 
                    <p><a target="_blank" style="text-decoration: none; color: black;" href="https://www.google.com/maps/place/Gopalganj,+Bihar+841428/data=!4m2!3m1!1s0x39931ace38b4be2b:0xed4849770012e298?sa=X&ved=2ahUKEwjZ0_v1mP76AhVwgtgFHb3pCTUQ8gF6BAgIEAE">Gopalganj, 841501, India</a></p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+91 XXXX 921786</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    
                    <p><a target="_blank" style="text-decoration: none; color: black;" href="https://mail.google.com/mail/u/0/#sent?compose=GTvVlcSHxTsKBkTWlDJHTDLzBZdBkQSdnXnjZnfhLpSRcCDVpdVrZKjckcXXnmTDdcLgxKNcCgKlg">mehdialam2002@gmail.com</a></p>

                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->







{% endblock  %}

wesapp/templates/home01.html
{% extends 'base.html' %}
{% block content %}

{% include 'home_body.html' %}

{% endblock  %}

wesapp/templates/update_post.html
<!-- {{post.title_tag}}


    

<h1>Edit Blog Post</h1>


<form action="" method="post" encrypt="multipart/form-data">
   {% csrf_token %}
   {{form.as_p}}
   {{ form.media}}
   
   <button>Update</button>
</form>  -->


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<style>
.forrm{
   margin-top: 40px;
   margin-left: 300px;
   margin-right: 400px;
   padding: 19px;
   box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;

}
.post_cancel{
   display: flex;
   justify-content: space-between;
  
}
.canc{
   display: flex;
   justify-content: space-between;
}
</style>




    


<!-- 

<form class="forrm" action="" method="post" encrypt="multipart/form-data">
   {% csrf_token %}
   <h1>Edit Blog Post</h1>
   <input type="hidden" >
   <p><label for="id_title"><strong>Title:</strong></label> <input type="text" name="title" value="Things to buy in Dhanteras 2022" maxlength="255" required id="id_title"></p>
<p><label for="id_content"><strong>Content:</strong></label> <input type="text" name="content" value="For the most part, purchasing gold and silver in one form or another marks Dhanteras, which is regarded as a holy day for making new purchases. However, very few people take advantage of the chance to invest in financial instruments that increase" maxlength="255" required id="id_content"></p>
   
  <div class="canc">
    
   <button class="btn btn-success">Update</button>
   <a href="/feed" class="btn btn-danger">Cancel</a>
  </div>
</form>

 -->


<form class="forrm" action="" method="post" encrypt="multipart/form-data">
   {% csrf_token %}
   <h1>Edit Blog Post</h1>
   <input type="hidden"  >
   <p><label for="id_title">Title:</label>
       <input type="text" class="form-control" name="title"  maxlength="255" required id="id_title"></p>
<p><label for="id_content2">Content2:</label>
    <textarea class="form-control" name="content2" cols="30" rows="7" required id="id_content2">
</textarea></p>
   
<div class="canc">
    
   <button class="btn btn-success">Update</button>
   <a href="/feed" class="btn btn-danger">Cancel</a>
  </div>
</form>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>  